src/main/java/ee/carlrobert/codegpt/toolwindow/chat/ChatToolWindowTabPanelEditor.java
=> 211 - Ability to create new files from codegpt toolwindow editor

buildSrc/src/main/kotlin/codegpt.java-conventions.gradle.kts, src/main/java/ee/carlrobert/codegpt/CodeGPTPlugin.java, src/main/java/ee/carlrobert/codegpt/completions/CompletionClientProvider.java, src/main/java/ee/carlrobert/codegpt/completions/CompletionRequestHandler.java, src/main/java/ee/carlrobert/codegpt/completions/CompletionRequestProvider.java, src/main/java/ee/carlrobert/codegpt/settings/YouServiceSelectionPanel.java, src/main/java/ee/carlrobert/codegpt/toolwindow/chat/BaseChatToolWindowTabPanel.java
* Bump llm-client to 0.0.6
* Design improvements
* Add additional params when making a completion request
=> You.com service updates

buildSrc/src/main/kotlin/codegpt.java-conventions.gradle.kts, codegpt-core/src/main/resources/prompts/method-name-generator.txt, src/main/java/ee/carlrobert/codegpt/PluginStartupActivity.java, src/main/java/ee/carlrobert/codegpt/completions/CompletionClientProvider.java, src/main/java/ee/carlrobert/codegpt/completions/CompletionLookupService.java, src/main/java/ee/carlrobert/codegpt/completions/CompletionRequestProvider.java, src/main/java/ee/carlrobert/codegpt/settings/configuration/ConfigurationComponent.java, src/main/java/ee/carlrobert/codegpt/settings/configuration/ConfigurationConfigurable.java, src/main/java/ee/carlrobert/codegpt/settings/configuration/ConfigurationState.java, src/main/resources/messages/codegpt.properties
=> Support method name lookup generation

README.md
This aligns with the LICENSE file in this repo and on Jetbrains website, and is coherent with https://github.com/carlrobertoh/CodeGPT/issues/275
=> Fix license in README.md

src/main/java/ee/carlrobert/codegpt/completions/llama/PromptTemplate.java, src/main/java/ee/carlrobert/codegpt/toolwindow/chat/standard/ModelComboBoxAction.java
Remote server enhancement, add template suport for DeepSeek Coder
=> feat: remote server, add template suport for DeepSeek Coder

src/main/java/ee/carlrobert/codegpt/completions/llama/PromptTemplate.java, src/main/java/ee/carlrobert/codegpt/settings/GeneralSettingsComponent.java, src/main/java/ee/carlrobert/codegpt/settings/service/llama/LlamaSettingsState.java, src/main/java/ee/carlrobert/codegpt/settings/service/llama/form/LlamaServerPreferencesForm.java
Enabled remote server for Windows:
- Mixtral Instruct template was added.
=> Enable remote server settings for Windows + Mixtral Instruct template

buildSrc/src/main/kotlin/codegpt.java-conventions.gradle.kts, src/main/java/ee/carlrobert/codegpt/completions/CompletionRequestProvider.java, src/main/java/ee/carlrobert/codegpt/settings/service/you/YouSettings.java, src/main/java/ee/carlrobert/codegpt/settings/service/you/YouSettingsState.java, src/main/java/ee/carlrobert/codegpt/toolwindow/chat/ui/ChatMessageResponseBody.java, src/main/java/ee/carlrobert/codegpt/toolwindow/chat/ui/textarea/ModelComboBoxAction.java, src/main/java/ee/carlrobert/codegpt/toolwindow/chat/ui/textarea/UserPromptTextAreaHeader.java, src/test/java/ee/carlrobert/codegpt/completions/DefaultCompletionRequestHandlerTest.java
It adds support for several new search modes: Default, Agent, Custom with various 3rd party models and Research
Depends on lllm-client changes here: https://github.com/carlrobertoh/llm-client/pull/16
=> Implement support for You Pro modes

src/main/java/ee/carlrobert/codegpt/actions/GenerateGitCommitMessageAction.java
1. Change the method we use to retrieve files that were changed and included in the commit. The old method did not work as mentioned in issue #338. I followed the advice provided [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/10709161728018/comments/10729508917266).
2. Remove the "--cached" option when retrieving the `git diff` because the Idea does not perform a `git add` when a file is selected. As a result, with the cached option, we encounter an empty diff.
3. For unversioned files, add the file content to the prompt as well since there is no way to force `git diff` to show these files.
=> fix: correctly handle changed files to generate a commit message #338

build.gradle.kts, buildSrc/src/main/kotlin/codegpt.java-conventions.gradle.kts, gradle/libs.versions.toml, src/main/java/ee/carlrobert/codegpt/completions/you/auth/YouAuthenticationService.java
* Cleaned versions catalog and dependencies
* Fixed checkstyle finding
=> chore(deps): Update checkstyle to 10.15.0

gradle.properties, src/main/java/ee/carlrobert/codegpt/completions/CompletionRequestService.java
* Use first non-blank choice from response
=> Update to latest 233 platform 2023.3.6

src/main/kotlin/ee/carlrobert/codegpt/credentials/CredentialsStore.kt
I believe this fixes the currently reported issues where credentials are not persisted between application restarts.
* https://github.com/carlrobertoh/CodeGPT/issues/457
* https://github.com/carlrobertoh/CodeGPT/issues/411
=> Persist credential changes into the PasswordSafe

build.gradle.kts, codegpt-telemetry/build.gradle.kts, codegpt-telemetry/src/main/java/ee/carlrobert/codegpt/telemetry/core/service/segment/IdentifyTraitsPersistence.java, gradle/libs.versions.toml, src/main/java/ee/carlrobert/codegpt/actions/IncludeFilesInContextAction.java, src/test/kotlin/ee/carlrobert/codegpt/telemetry/core/service/segment/IdentifyTraitsPersistenceTest.kt
Old Gson couldn't serialize records since Java 16.
=> fix: Telemetry can't serialize traits anymore

src/main/java/ee/carlrobert/codegpt/completions/HuggingFaceModel.java, src/main/java/ee/carlrobert/codegpt/settings/service/llama/form/LlamaModelPreferencesForm.java
=> feat: Add Llama 3 download sizes

src/main/java/ee/carlrobert/codegpt/completions/llama/LlamaModel.java, src/main/java/ee/carlrobert/codegpt/completions/llama/PromptTemplate.java, src/main/java/ee/carlrobert/codegpt/settings/service/llama/LlamaSettingsState.java, src/main/kotlin/ee/carlrobert/codegpt/codecompletions/InfillPromptTemplate.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/CustomServiceCodeCompletionForm.kt
This PR enable Code-Completions for `CodeGemma` (see https://huggingface.co/google/codegemma-7b#for-code-completion)
Also closes #524
=> feat: add CodeGemma InfillPromptTemplate

src/main/java/ee/carlrobert/codegpt/completions/HuggingFaceModel.java, src/main/java/ee/carlrobert/codegpt/completions/llama/LlamaModel.java, src/main/java/ee/carlrobert/codegpt/completions/llama/PromptTemplate.java, src/main/kotlin/ee/carlrobert/codegpt/codecompletions/InfillPromptTemplate.kt, src/test/kotlin/ee/carlrobert/codegpt/completions/PromptTemplateTest.kt
https://qwenlm.github.io/blog/codeqwen1.5/
> CodeQwen1.5-7B has been pretrained with around 3 trillion tokens of code-related data. It supports an extensive repertoire of 92 programming languages, and it exhibits exceptional capacity in long-context understanding and generation with the ability to process information of 64K tokens.
In terms of performance, CodeQwen1.5 demonstrates impressive capabilities in basic code generation, long-context modelling, code editing and SQL. We believe this model can significantly enhance developer productivity and streamline software development workflows within diverse technological environments.
=> feat: Support CodeQwen1.5-Chat model

src/main/java/ee/carlrobert/codegpt/settings/service/llama/form/LlamaModelPreferencesForm.java, src/main/kotlin/ee/carlrobert/codegpt/CodeGPTProjectActivity.kt, src/main/kotlin/ee/carlrobert/codegpt/FileWatcher.kt, src/main/kotlin/ee/carlrobert/codegpt/codecompletions/CodeGPTInlineCompletionProvider.kt
* Code completions enabled but LLaMA model doesn't support them
* Checking for new screenshots enabled but folder not accessible or WatchService fails
* LLaMA preferences calculate download state on opening settings, not after switching models
=> fix: Handle problems graciously

src/main/java/ee/carlrobert/codegpt/completions/HuggingFaceModel.java, src/main/java/ee/carlrobert/codegpt/completions/llama/LlamaModel.java
https://azure.microsoft.com/en-us/blog/introducing-phi-3-redefining-whats-possible-with-slms/
https://huggingface.co/microsoft/Phi-3-medium-128k-instruct
https://huggingface.co/bartowski/Phi-3-medium-128k-instruct-GGUF
=> feat: Support Phi-3 Medium 128K

src/main/java/ee/carlrobert/codegpt/settings/service/llama/form/LlamaServerPreferencesForm.java, src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/form/CustomServiceChatCompletionForm.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/form/CustomServiceCodeCompletionForm.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/ollama/OllamaSettingsForm.kt, src/main/kotlin/ee/carlrobert/codegpt/ui/URLTextField.kt
=> fix: remove trailing slashes from URL text fields

src/main/java/ee/carlrobert/codegpt/completions/HuggingFaceModel.java, src/main/java/ee/carlrobert/codegpt/completions/llama/LlamaModel.java, src/main/kotlin/ee/carlrobert/codegpt/codecompletions/InfillPromptTemplate.kt, src/test/kotlin/ee/carlrobert/codegpt/completions/PromptTemplateTest.kt
https://mistral.ai/news/codestral/
https://huggingface.co/bartowski/Codestral-22B-v0.1-GGUF
https://huggingface.co/lmstudio-community/Codestral-22B-v0.1-GGUF
https://ollama.com/library/codestral
Still downloading... can you try if prompt and FIM work?
As always the hardest part is figuring out the templates and (stop) tokens, every source says something different...
Would be too easy if there would be standardized model cards containing the info needed to run and use the model, guess we need much more AI to figure that out 🤦
The license is "for research and testing purposes", is it possible to merge?
=> Draft: feat: Support Codestral 22B 32K

src/main/java/ee/carlrobert/codegpt/settings/service/custom/CustomServiceFormTabbedPane.java
Minor fix for issue : https://github.com/carlrobertoh/CodeGPT/issues/619
=> Numeric values in Custom providers' headers section break configuration #619

src/main/kotlin/ee/carlrobert/codegpt/settings/service/ollama/OllamaSettingsForm.kt
for issue #616 
1) sort ollama models list when select the model from settings 
2) fix: settings of cached ollama models need update 
3) sort cached ollama models
=> issue#616 code

src/main/kotlin/ee/carlrobert/codegpt/codecompletions/CodeCompletionService.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/CustomServiceSettings.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/form/CustomServiceCodeCompletionForm.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/form/CustomServiceForm.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/template/CustomServiceCodeCompletionTemplate.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/template/CustomServiceTemplate.kt, src/main/resources/messages/codegpt.properties
fixes https://github.com/carlrobertoh/CodeGPT/issues/723
=> feat: support of parsing Custom OpenAI response as Code Completions

src/main/kotlin/ee/carlrobert/codegpt/settings/prompts/form/PromptsForm.kt
=> fix: use correct array indices (#928)

src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/CustomServiceConfigurable.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/form/CustomServiceListForm.kt, src/main/kotlin/ee/carlrobert/codegpt/util/coroutines/CoroutineDispatchers.kt, src/main/kotlin/ee/carlrobert/codegpt/util/coroutines/EdtCoroutineDispatcher.kt, src/main/kotlin/ee/carlrobert/codegpt/util/coroutines/EdtCoroutineDispatcherExtensions.kt
On recent versions of the IntelliJ Idea core, there was a problem with rendering the UI on the form of adding Custom Open AI Settings. Implemented Coroutine Dispatcher for the correct operation of interface rendering on EDT.
Before:
https://github.com/user-attachments/assets/d794933d-1544-463f-a930-c32271e3505a
After fix:
Android Studio
https://github.com/user-attachments/assets/0a7049bc-1f1e-4c74-b9da-46556c462147
IntelliJ Idea:
https://github.com/user-attachments/assets/7a88233a-00e5-4bd3-b743-42e10d257103
=> Fix custom open ai settings UI

src/main/java/ee/carlrobert/codegpt/actions/toolwindow/ClearChatTagsAction.kt, src/main/java/ee/carlrobert/codegpt/toolwindow/chat/ChatToolWindowContentManager.java, src/main/java/ee/carlrobert/codegpt/toolwindow/chat/ChatToolWindowTabPanel.java, src/main/kotlin/ee/carlrobert/codegpt/util/coroutines/DisposableCoroutineScope.kt, src/main/resources/META-INF/plugin.xml
Clear active chat tag by keyboard shortcut - "Ctrl+Alt+Shift+T".
https://github.com/user-attachments/assets/14319d43-7a15-4930-a702-6efa62ec8f23
=> feat: clear chat tag by keyboard shortcut

.gitignore, build.gradle.kts
Add local.properties to gitignore and register runCustomIdea task using customIdeaPath property.
=> Custom sandbox runIdeTask
