src/main/java/ee/carlrobert/codegpt/toolwindow/components/TextArea.java
- based on the IntelliJ Platform UI Guidelines https://jetbrains.design/intellij/controls/input_field/#placeholder "Hide the placeholder when the user starts typing, not when the input field gets the focus."
- remove focus event and listener
I was running into an issue where if you paste by using middle click in Linux, the placeholder text would not be erased first, and the pasted text and the placeholder end up being combined.
=> Change how placeholder text is displayed and hidden

src/main/java/ee/carlrobert/codegpt/settings/ServiceSelectionForm.java, src/main/java/ee/carlrobert/codegpt/settings/SettingsComponent.java, src/main/java/ee/carlrobert/codegpt/settings/SettingsConfigurable.java, src/main/java/ee/carlrobert/codegpt/settings/configuration/ConfigurationConfigurable.java
Currently the following error occurs when compiling the plugin.
```
Memory leak detected: 'ee.carlrobert.codegpt.settings.SettingsConfigurable@4bcf0b26' (class ee.carlrobert.codegpt.settings.SettingsConfigurable) was registered in Disposer as a child of 'ROOT_DISPOSABLE' (class com.intellij.openapi.util.Disposer$2) but wasn't disposed.
Register it with a proper parentDisposable or ensure that it's always disposed by direct Disposer.dispose call.
See https://jetbrains.org/intellij/sdk/docs/basics/disposers.html for more details.
```
According to the [documentation](https://plugins.jetbrains.com/docs/intellij/disposers.html#automatically-disposed-objects), extensions registered in `plugin.xml` are not automatically disposed causing this error.
So defining [a disposable …
=> Fix memory leak in extensions

src/main/java/ee/carlrobert/codegpt/toolwindow/chat/components/UserPromptTextArea.java
Issue #174 fixed.
before:
after:
=> Set line wrap style to be wrapped at word boundaries

src/main/java/ee/carlrobert/codegpt/settings/service/LlamaServiceSelectionForm.java
After adding the **Additional parameters** field, a problem arose with running local models. The problem is that if the **Additional parameters** field is left empty, then an empty parameter is added to the command line. It looks like this:
```./server -m /home/user/path/to/model/codellama-13b-instruct.Q4_K_M.gguf -c 2048 --port 39193 -t 20 ""```
Pay attention to the end of the line: `""`
Thus, the server does not start and on the screen we see the error: **Server Terminated**
This pull request fixes this issue.
=> Local LLM: Added empty check for `Additional parameters` field

src/main/resources/META-INF/plugin.xml
The CodeGPT Telemetry settings screen was previously a 'stand-alone' configuration window under the 'Tools' section of the IDEA settings. Moving it under the parent plugin makes it more apparent and keeps it better organized.
=> Move the CodeGPT Telemetry settings screen.

src/main/java/ee/carlrobert/codegpt/completions/llama/LlamaServerAgent.java, src/main/java/ee/carlrobert/codegpt/completions/llama/LlamaServerStartupParams.java, src/main/java/ee/carlrobert/codegpt/settings/service/LlamaModelPreferencesForm.java, src/main/java/ee/carlrobert/codegpt/settings/service/LlamaServiceSelectionForm.java, src/main/java/ee/carlrobert/codegpt/settings/service/ServiceSelectionForm.java, src/main/java/ee/carlrobert/codegpt/settings/state/LlamaSettingsState.java, src/main/java/ee/carlrobert/codegpt/ui/UIUtil.java, src/main/resources/messages/codegpt.properties
Fixes #335 by adding new option in the settings to use a custom pre-compiled LLama Server:
When `use custom-server` is selected it will run the configured custom server without compiling.
=> Add setting for custom LLama server executable

src/main/java/ee/carlrobert/codegpt/completions/CompletionClientProvider.java
Currently proxy settings aren't considered when performing a request with the Azure service.
=> Respect proxy settings for Azure Client

src/main/java/ee/carlrobert/codegpt/codecompletions/InfillPromptTemplate.java
@carlrobertoh @PhilKes 
Fix completion prompt template for DeepSeek Coder.
'<|fim_begin|>' -> '<｜fim▁begin｜>', they are different. Which is why the outputs so bad.
Reference: https://github.com/deepseek-ai/DeepSeek-Coder
BTW, I tested it with the original version of DeepSeek Coder 6.7B and 33B, quantized models have accuracy loss.
=> fix: completion prompt template for Deepseek Coder

src/main/java/ee/carlrobert/codegpt/ui/checkbox/PsiElementCheckboxTree.java
[Solves this issue](https://github.com/carlrobertoh/CodeGPT/issues/342). It seems that single Java files are represented as PsiClass in the Psi hierarchy rather than PsiFile. The class has a method `getContainingFile` that resolves the file so I've simply delegated to that in these cases.
=> bugfix: Allow single Java files to be added to context

src/main/java/ee/carlrobert/codegpt/EncodingManager.java
Fixes https://github.com/carlrobertoh/CodeGPT/issues/444
Now countTokens() catches `Errors` too like such encoding errors `Input is not UTF-8: `.
Like with exceptions, they will be logged in idea.log and 0 will be used for this input text.
=> fix: Catch AssertionError in countTokens()

src/main/java/ee/carlrobert/codegpt/completions/CompletionRequestProvider.java, src/main/java/ee/carlrobert/codegpt/settings/configuration/ConfigurationComponent.java, src/main/java/ee/carlrobert/codegpt/settings/configuration/ConfigurationSettings.java, src/main/java/ee/carlrobert/codegpt/toolwindow/chat/ui/textarea/TotalTokensDetails.java, src/test/kotlin/ee/carlrobert/codegpt/completions/CompletionRequestProviderTest.kt, src/test/kotlin/ee/carlrobert/codegpt/completions/DefaultCompletionRequestHandlerTest.kt, src/test/kotlin/ee/carlrobert/codegpt/toolwindow/chat/ChatToolWindowTabPanelTest.kt
Use the default System Prompt only for filling the configuration form initially.
=> fix: Use System Prompt from user configuration (#454)

src/main/java/ee/carlrobert/codegpt/settings/GeneralSettings.java, src/test/kotlin/ee/carlrobert/codegpt/settings/state/GeneralSettingsTest.kt
This is a continuation from comments in #466, we should handle `custom.openai.chat.completion` in GeneralSettings.sync
=> Handle custom.openai.chat.completion in GeneralSettings.sync

src/main/kotlin/ee/carlrobert/codegpt/codecompletions/CodeGPTInlineCompletionProvider.kt
- Stream completion results character by character to provide a more responsive user experience
- Cancel the completion request early when a newline character is encountered to save token usage costs
These changes improve performance, reduce costs, and enhance the overall user experience. Please review and provide feedback.
The current completion suggestion implementation waits for all results before returning the content before the first newline character. This approach is slow and wastes token usage.
```
val output =
if (messageBuilder.contains("\n"))
messageBuilder.substring(0, messageBuilder.indexOf("\n"))
else messageBuilder.toString()
completed(output)
```
By the way, I am a colleague of wsxqyws and I am taking over his work to implement the streaming completion feature for CodeGPT …
=> Stream code completion and cancel early on newline

build.gradle.kts, src/main/java/ee/carlrobert/codegpt/completions/llama/LlamaServerAgent.java, src/main/java/ee/carlrobert/codegpt/completions/llama/LlamaServerStartupParams.java, src/main/java/ee/carlrobert/codegpt/settings/service/llama/LlamaSettingsState.java, src/main/java/ee/carlrobert/codegpt/settings/service/llama/form/LlamaServerPreferencesForm.java, src/main/java/ee/carlrobert/codegpt/settings/service/llama/form/LlamaSettingsForm.java, src/main/java/ee/carlrobert/codegpt/settings/service/llama/form/ServerProgressPanel.java, src/main/java/ee/carlrobert/codegpt/ui/OverlayUtil.java, src/main/resources/messages/codegpt.properties
This PR closes #405 
- Adds new input field for Llama-CPP Server build parameters to e.g. enable using GPU via CUDA or similar:
- Improved error handling when building or running server fails:
=> feat: add input field for llama server build parameters

src/main/java/ee/carlrobert/codegpt/completions/HuggingFaceModel.java, src/main/java/ee/carlrobert/codegpt/completions/llama/LlamaModel.java, src/main/java/ee/carlrobert/codegpt/completions/llama/PromptTemplate.java, src/main/kotlin/ee/carlrobert/codegpt/codecompletions/InfillPromptTemplate.kt, src/test/kotlin/ee/carlrobert/codegpt/completions/PromptTemplateTest.kt
Wow, fresh of the press, seems to be one of the best models now!! 🚀
Waiting for llama.cpp support... 😅
https://github.com/ggerganov/llama.cpp/issues/6747
https://github.com/ggerganov/llama.cpp/pull/6751
=> Draft: feat: Support Llama 3 model (#478)

src/main/java/ee/carlrobert/codegpt/settings/service/llama/LlamaSettings.java, src/main/kotlin/ee/carlrobert/codegpt/actions/CodeCompletionFeatureToggleActions.kt
Most Llama models don't support code completions (only Code Llama and Deepseek Coder).
This PR fixes the NPE that was produced and adds support for Llama 3.
I guess #495 beginning of empty line is not possible with com.intellij.codeInsight.inline.completion.elements.InlineCompletionGrayTextElement.Presentable#render returning on empty text.
But entering tabulators shows no completion either.
Any number of spaces shows completions.
But when followed by a backspace (some spaces deleted), completions disappear again 😅
=> fix: Unsupported code completions

src/main/java/ee/carlrobert/codegpt/completions/CompletionRequestService.java, src/main/kotlin/ee/carlrobert/codegpt/codecompletions/CodeCompletionRequestFactory.kt, src/test/kotlin/ee/carlrobert/codegpt/codecompletions/CodeCompletionServiceTest.kt
Use `/infill` for Llama.CPP code-completions instead of `/chat/completions` as suggested in https://github.com/carlrobertoh/CodeGPT/pull/510#issuecomment-2077027810
=> fix: use /infill for llama.cpp code-completions

src/main/java/ee/carlrobert/codegpt/settings/configuration/ConfigurationComponent.java, src/main/java/ee/carlrobert/codegpt/settings/configuration/ConfigurationConfigurable.java
This PR fixes #381
- Refreshes Editor Actions after Configuration apply
- Focuses new row when new Editor Action is added (+):
=> fix: focus on new editor action and refresh editor actions on apply

src/main/resources/META-INF/plugin.xml
This PR fixes #522 and fixes #523
Tested with:
Ubuntu 22.04
Pycharm Community 2023.3.5
Without the fix:
https://github.com/carlrobertoh/CodeGPT/blob/6d6e0a3ccb739ff9a08a35ce06a7d342cf2510a4/src/main/kotlin/ee/carlrobert/codegpt/settings/configuration/Placeholder.kt#L29
Throws when trying to generate a commit message:
```java
Caused by: java.lang.ClassNotFoundException: git4idea.GitUtil PluginClassLoader(plugin=PluginDescriptor(name=CodeGPT, id=ee.carlrobert.chatgpt, descriptorPath=plugin.xml, path=~/IdeaProjects/git/CodeGPT/build/idea-sandbox/plugins/CodeGPT, version=2.6.3-233, package=null, isBundled=false), packagePrefix=null, state=active)
```
=> fix: add optional Git4Idea dependency to plugin.xml

src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/CustomServiceChatCompletionTemplate.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/CustomServiceTemplate.kt
This PR closes #403 
Adds `CustomServiceTemplate` for [Mistral AI API](https://docs.mistral.ai/getting-started/quickstart/)
=> feat: add Mistral AI service template

src/main/java/ee/carlrobert/codegpt/settings/GeneralSettingsComponent.java, src/main/kotlin/ee/carlrobert/codegpt/settings/service/ollama/OllamaSettingsForm.kt
The `refreshModels()` was initially called in the constructor of `OllamaSettingsForm`.
Because of this whenever the user opens the settings the GET `/api/tags` request is triggered to refresh the Ollama models, even if Ollama is not even the currently selected service
=> fix: refresh Ollama models only when service is changed to Ollama

gradle/libs.versions.toml, src/main/java/ee/carlrobert/codegpt/Icons.java, src/main/java/ee/carlrobert/codegpt/completions/CompletionClientProvider.java, src/main/java/ee/carlrobert/codegpt/completions/CompletionRequestProvider.java, src/main/java/ee/carlrobert/codegpt/completions/CompletionRequestService.java, src/main/java/ee/carlrobert/codegpt/conversations/ConversationService.java, src/main/java/ee/carlrobert/codegpt/settings/GeneralSettings.java, src/main/java/ee/carlrobert/codegpt/settings/GeneralSettingsComponent.java, src/main/java/ee/carlrobert/codegpt/settings/GeneralSettingsConfigurable.java, src/main/java/ee/carlrobert/codegpt/settings/service/ServiceType.java, src/main/java/ee/carlrobert/codegpt/toolwindow/chat/ui/textarea/ModelComboBoxAction.java, src/main/java/ee/carlrobert/codegpt/ui/ModelIconLabel.java, src/main/kotlin/ee/carlrobert/codegpt/actions/CodeCompletionFeatureToggleActions.kt, src/main/kotlin/ee/carlrobert/codegpt/codecompletions/CodeGPTInlineCompletionProvider.kt, src/main/kotlin/ee/carlrobert/codegpt/credentials/CredentialsStore.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/google/GoogleSettings.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/google/GoogleSettingsForm.kt, src/main/resources/META-INF/plugin.xml, src/main/resources/icons/google.svg, src/main/resources/messages/codegpt.properties, src/test/kotlin/ee/carlrobert/codegpt/completions/DefaultCompletionRequestHandlerTest.kt, src/test/kotlin/testsupport/mixin/ShortcutsTestMixin.kt
This PR closes #310.
Adds support for Google's [Gemini API](https://ai.google.dev/api/rest/v1/models?&authuser=1) 
Blocked by:
Notes:
- Gemini Vision models do not support Chats yet, therefore you can't send images in chat
- There is currently no Gemini model with FIM, therefore no code-completions
=> feat: add Google Gemini API support

src/main/kotlin/ee/carlrobert/codegpt/actions/editor/ShowEditorActionGroupAction.kt, src/main/resources/META-INF/plugin.xml
This PR closes #314
Adds Action to show CodeGPT Actions popup with keyboard shortcut:
All Actions are assigned an alpha-numeric letter for seamless keyboard controls.
I didn't really know how to define the best default shortcut, so I sticked with the  `CTRL+SHIFT+ALT` combo plus "M" (maybe "M" for "Menu"?), that doesn't seem to be used by anything too important:
=> feat: add keyboard shortcuts for Editor actions

src/main/java/ee/carlrobert/codegpt/actions/GenerateGitCommitMessageAction.java, src/main/java/ee/carlrobert/codegpt/completions/CompletionRequestProvider.java, src/main/java/ee/carlrobert/codegpt/completions/CompletionRequestService.java, src/main/java/ee/carlrobert/codegpt/completions/HuggingFaceModel.java, src/main/java/ee/carlrobert/codegpt/completions/llama/LlamaModel.java, src/main/java/ee/carlrobert/codegpt/conversations/ConversationService.java, src/main/java/ee/carlrobert/codegpt/settings/GeneralSettings.java, src/main/java/ee/carlrobert/codegpt/settings/service/llama/form/LlamaModelPreferencesForm.java, src/main/java/ee/carlrobert/codegpt/toolwindow/chat/ChatToolWindowTabPanel.java, src/main/java/ee/carlrobert/codegpt/toolwindow/chat/ui/ChatToolWindowScrollablePanel.java, src/main/java/ee/carlrobert/codegpt/toolwindow/chat/ui/textarea/ModelComboBoxAction.java, src/main/java/ee/carlrobert/codegpt/toolwindow/chat/ui/textarea/TotalTokensPanel.java, src/main/java/ee/carlrobert/codegpt/toolwindow/chat/ui/textarea/UserPromptTextArea.java, src/main/kotlin/ee/carlrobert/codegpt/actions/CodeCompletionFeatureToggleActions.kt, src/main/kotlin/ee/carlrobert/codegpt/codecompletions/CodeCompletionService.kt, src/main/kotlin/ee/carlrobert/codegpt/codecompletions/CodeGPTInlineCompletionProvider.kt
With more and more LLaMA models users should have a clear path to select/switch one of their downloaded models in as few clicks as possible.
=> feat: Visualize downloaded models

src/main/java/ee/carlrobert/codegpt/completions/HuggingFaceModel.java, src/main/java/ee/carlrobert/codegpt/completions/llama/LlamaModel.java, src/main/java/ee/carlrobert/codegpt/completions/llama/PromptTemplate.java, src/main/java/ee/carlrobert/codegpt/settings/service/llama/form/LlamaModelPreferencesForm.java, src/test/kotlin/ee/carlrobert/codegpt/completions/PromptTemplateTest.kt
https://stability.ai/news/introducing-stable-code-instruct-3b
https://huggingface.co/stabilityai/stable-code-instruct-3b
https://huggingface.co/bartowski/stable-code-instruct-3b-GGUF
https://ollama.com/library/stable-code
Prompt seems identical to Code Qwen, but I had to add `<|im_end|>` as stop token.
Can you try it out, FIM isn't possible with the instruct model, right?
Too bad we can't run 2 models after each other like I proposed...
* User enters chat window focus, start Instruct model automatically (stop FIM if running)
* User leaves chat window focus, start Code Completion model automatically (stop Instruct if running)
For example
https://huggingface.co/google/codegemma-7b
https://huggingface.co/google/codegemma-7b-it
https://huggingface.co/meta-llama/Meta-Llama-3-8B …
=> feat: Support Stable Code Instruct 3B

src/main/java/ee/carlrobert/codegpt/completions/llama/LlamaServerAgent.java, src/main/java/ee/carlrobert/codegpt/completions/llama/LlamaServerStartupParams.java, src/main/java/ee/carlrobert/codegpt/settings/service/llama/LlamaSettings.java, src/main/java/ee/carlrobert/codegpt/settings/service/llama/LlamaSettingsState.java, src/main/java/ee/carlrobert/codegpt/settings/service/llama/form/LlamaServerPreferencesForm.java, src/main/java/ee/carlrobert/codegpt/settings/service/llama/form/LlamaSettingsForm.java, src/main/kotlin/ee/carlrobert/codegpt/actions/LlamaServerToggleActions.kt, src/main/resources/messages/codegpt.properties
This PR closes #549 
Adds new text input field for setting additional environment variables for the LlamaCPP server to enable setting e.g. [CUDA variables](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars)
=> feat: add field for environment variables for Llama server

src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/template/CustomServiceChatCompletionTemplate.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/template/CustomServiceTemplate.kt
This PR adds a Custom OpenAI Service template for [OpenRouter](https://openrouter.ai/docs#quick-start)
(Motivation: https://github.com/carlrobertoh/CodeGPT/issues/310#issuecomment-2129951826)
=> feat: add OpenRouter service template

src/main/java/ee/carlrobert/codegpt/completions/llama/LlamaModel.java, src/main/kotlin/ee/carlrobert/codegpt/codecompletions/InfillPromptTemplate.kt
Hi @carlrobertoh,
Thank you for sharing this awesome project! 
Please accept my humble contributions to fix the Codestral model for code completion, for which I use locally in llama.cpp.
Thank you,
Nick
=> Fix Codestral Infill templates for code completion in llama.cpp

src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/template/CustomServiceChatCompletionTemplate.kt
- Updated the model version for the OpenRouter configuration in the custom OpenAI provider from `meta-llama/llama-3-8b-instruct:free` to `meta-llama/llama-3.1-8b-instruct:free`
=> fix: update OpenRouter model version in custom OpenAI provider

src/main/java/ee/carlrobert/codegpt/toolwindow/chat/ui/textarea/ModelComboBoxAction.java, src/main/kotlin/ee/carlrobert/codegpt/settings/service/codegpt/CodeGPTAvailableModels.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/codegpt/CodeGPTServiceForm.kt
this hides all the services in the ModelCB which require an API key but don't have one configured.
also only the CodeGPT models which are in the users current PricingPlan are shown.
=> feat(ui): hide services with missing api key & models not in users pricing plan

src/main/kotlin/ee/carlrobert/codegpt/ui/textarea/header/tag/TagPanel.kt, src/main/kotlin/ee/carlrobert/codegpt/ui/textarea/suggestion/SuggestionsPopupManager.kt
Fixed the display of tags when the font size is 15 and higher. I changed the pop-up display on macOS, when using multiple screens, the pop-up was shown on the main screen, although the IDE was on another one.
↓
=> Fix suggestions popup positioning and tag panel styling

src/main/java/ee/carlrobert/codegpt/completions/CompletionClientProvider.java, src/main/java/ee/carlrobert/codegpt/settings/service/anthropic/AnthropicSettingsForm.java, src/main/java/ee/carlrobert/codegpt/settings/service/anthropic/AnthropicSettingsState.java
Certain organizations use their own proxies for AI tools. Multiple tools, including Cline, offer support for custom hosts/URLs to accommodate these proxies.
- add custom host setting
- use jetbrains-provided tls bundle
The default okhttp3 bundle does not include additional certificates that might be installed on your system, so utilizing the JetBrains-provided TLS bundle ensures all necessary certificates are considered.
=> feat: custom base host support for anthropic privider

src/main/java/ee/carlrobert/codegpt/completions/llama/LlamaModel.java
When I first opened this tab, I didn't understand why the left indent was needed. Only then I realized that this is a description of the state of the model downloaded or not. 
As to me it is very confusing. After adding an icon, you can realize that the model still needs to be downloaded.
=> new icon to indicate that LLaMA model is not downloaded

src/main/kotlin/ee/carlrobert/codegpt/util/EditorUtil.kt
Fixes #1065, Fixes #1059, Fixes #1059, Fixes #1006,Fixes #1003.
All of these issues seem to point to this particular bit, where a virtual file is created while on the EDT.
(I references #1006 specifically in the commit message, as that issue contains the most info describing the problem)
=> fix: EditorUtil.createEditor() creates files on EDT

src/main/kotlin/ee/carlrobert/codegpt/actions/CodeCompletionFeatureToggleActions.kt, src/main/kotlin/ee/carlrobert/codegpt/codecompletions/CodeCompletionRequestFactory.kt, src/main/kotlin/ee/carlrobert/codegpt/codecompletions/CodeCompletionService.kt, src/main/kotlin/ee/carlrobert/codegpt/codecompletions/DebouncedCodeCompletionProvider.kt, src/main/kotlin/ee/carlrobert/codegpt/completions/factory/CustomOpenAIRequestFactory.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/CustomServiceSettings.kt
Fixes #1089 
My (second) hunch was correct. The `CustomOpenAIRequestFactory` as well as several points in the Code Completion logic referenced `ee.carlrobert.codegpt.settings.service.custom.CustomServicesState#getActive` but that property always contains the same (first) custom service definition state.
=> fix: Custom Open AI services do not adhere to model selections

src/main/kotlin/ee/carlrobert/codegpt/codecompletions/CodeCompletionRequestFactory.kt, src/main/kotlin/ee/carlrobert/codegpt/codecompletions/CodeCompletionService.kt, src/main/kotlin/ee/carlrobert/codegpt/codecompletions/InfillPromptTemplate.kt, src/main/kotlin/ee/carlrobert/codegpt/settings/service/custom/form/CustomServiceCodeCompletionForm.kt, src/test/kotlin/ee/carlrobert/codegpt/codecompletions/ChatBasedFIMTest.kt
@carlrobertoh: this is the only feature missing in ProxyAI to finally ditch Github Copilot!
FIM Code completion is done in ProxyAI using gpt-3.5-turbo-instruct via the `/v1/completions` endpoint only which is now [legacy](https://platform.openai.com/docs/guides/completions). Many OpenAI-compatible APIs do not support this endpoint.
I added Chat-based FIM code completion and tested with gpt-4.1.
May conflict with: https://github.com/carlrobertoh/ProxyAI/pull/1090, I could rebase if necessary.
Sample GPT-4.1 chat completion:
=> feat: chat-based FIM code completion for Custom OpenAI providers
